#!/bin/sh
set -e

# Check for kubectl installation
if command -v kubectl >/dev/null 2>&1; then
    echo "kubectl is already installed."
else
    echo "kubectl is not installed. Do you want to install it? (y/n)"
    read install_kubectl
    if [ "$install_kubectl" = "y" ]; then
        echo "Enter the Kubernetes version for kubectl (e.g., 1.21.0): "
        read KUBE_VERSION

        if ! echo "$KUBE_VERSION" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+$'; then
            echo "Invalid version format. Please specify in 'x.y.z' format."
            exit 1
        fi
        echo "Installing kubectl version $KUBE_VERSION..."
        curl -LO "https://dl.k8s.io/release/v${KUBE_VERSION}/bin/linux/amd64/kubectl"
        chmod +x kubectl
        mv kubectl /usr/local/bin/
    else
        echo "Skipping kubectl installation."
    fi
fi

# Check for awscli installation
if command -v aws >/dev/null 2>&1; then
    echo "awscli is already installed."
else
    echo "awscli is not installed. Do you want to install it? (y/n)"
    read install_awscli
    if [ "$install_awscli" = "y" ]; then
        echo "Installing awscli..."
        apt update
        apt install -y unzip curl
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -o awscliv2.zip
        ./aws/install
        rm -f awscliv2.zip
        rm -rf aws
    else
        echo "Skipping awscli installation."
    fi
fi

# Define the base directory for multikube
MULTIKUBE_DIR="/usr/local/bin/multikubeBin"

# Ensure the multikube directory exists
if [ ! -d "$MULTIKUBE_DIR" ]; then
    echo "Error: $MULTIKUBE_DIR does not exist. Installation failed."
    exit 1
fi

# Create a virtual environment inside the multikube directory
VENV_DIR="$MULTIKUBE_DIR/venv"
if [ ! -d "$VENV_DIR" ]; then
    echo "Creating virtual environment..."
    python3 -m venv "$VENV_DIR"
    echo "Installing dependencies from requirements.txt..."
    "$VENV_DIR/bin/pip" install -r "requirements.txt"
fi
# Set permissions for multikube.py
chmod +x "$MULTIKUBE_DIR/multikube.py"

if [ ! -L /usr/local/bin/multikube ]; then
    ln -s "$MULTIKUBE_DIR/multikube.py" /usr/local/bin/multikube
fi

echo "Installation completed successfully."
